dist: trusty
sudo: false

language: node_js
node_js:
  - '12.16.0'

addons:
  chrome: stable

before_script:
  - npm install @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng test
