dist: trusty
sudo: false

language: node_js
node_js:
  - '12.16.0'

addons:
  chrome: stable

before_script:
  - npm install @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: heroku
  api_key:
    secure: "25ddb900-50f8-4d89-9337-80bd723cb627"
