dist: trusty
sudo: false

language: node_js
node_js:
  - '12.16.0'

addons:
  chrome: stable

before_script:
  - npm install @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: heroku
  api_key:
    secure: "5d2821f6-21a0-4055-968a-48874b557471"
